"""Final fix for unaccented search columns

Revision ID: 8fc8479f1781
Revises: 7601cb40cbe9
Create Date: 2025-12-04 09:15:53.626779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc8479f1781'
down_revision = '7601cb40cbe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provinces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_unaccented', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_provinces_name_unaccented'), ['name_unaccented'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provinces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provinces_name_unaccented'))
        batch_op.drop_column('name_unaccented')

    # ### end Alembic commands ###
