"""Add estimated_duration_hours to Destination

Revision ID: a789a6da2716
Revises: 8fc8479f1781
Create Date: 2025-12-05 13:31:10.040339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a789a6da2716'
down_revision = '8fc8479f1781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_duration_hours', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.drop_column('estimated_duration_hours')

    # ### end Alembic commands ###
